draw_config:
  n_columns: 1
  dark_mode: auto

parse_config:
  raw_binding_map:
    "&kp LCTRL": "⌃"
    "&kp LSHIFT": "⇧"
    "&kp RSHIFT": "⇧"
    "&kp LALT": "⌥"
    "&kp TAB": "⇥"
    "&kp BACKSPACE": "⌫"
    "&kp DELETE": "⌦"
    "&kp ESC": "⎋"

    "&kp LEFT": "←"
    "&kp DOWN": "↓"
    "&kp UP": "↑"
    "&kp RIGHT": "→"

    "&lt 1 SPACE": { t: "␣", h: "Num" }

    "&enter_morph": { t: "⏎", h: "Num" }
    "&h_morph": { t: "h", h: "←" }
    "&j_morph": { t: "j", h: "↓" }
    "&k_morph": { t: "k", h: "↑" }
    "&l_morph": { t: "l", h: "→" }

    "&mkp LCLK": "L Click"
    "&mkp RCLK": "R Click"

    "&gch_ent": "Desktop ←"
    "&gcl_ent": "Desktop →"

    "&bt_toggle": "BT 0⇄1"

    "&msc MOVE_DOWN": "Scroll ↓"
    "&msc MOVE_UP": "Scroll ↑"
