draw_config:
  n_columns: 1
  dark_mode: auto

parse_config:
  raw_binding_map:
    "&kp LCTRL": "⌃"
    "&kp LSHIFT": "⇧"
    "&kp LALT": "⌥"
    "&kp TAB": "⇥"
    "&kp BACKSPACE": "⌫"
    "&kp DELETE": "⌦"
    "&kp ESC": "⎋"
    "&kp SPACE": "␣"

    "&kp LEFT": "←"
    "&kp DOWN": "↓"
    "&kp UP": "↑"
    "&kp RIGHT": "→"

    "&lt 1 ENTER": { t: "⏎", h: "Arrow" }
    "&lt 2 SPACE": { t: "␣", h: "Num" }

    "&h_morph": { t: "h", h: "←" }
    "&j_morph": { t: "j", h: "↓" }
    "&k_morph": { t: "k", h: "↑" }
    "&l_morph": { t: "l", h: "→" }

    "&lang1_sh2 0 LANG1": { t: "KANA", h: "⇧ Num" }
    "&lang2_gui": { t: "EISU", h: "⌘" }

    "&mkp LCLK": "L Click"
    "&mkp RCLK": "R Click"

    "&msc SCRL_DOWN": "Scroll ↓"
    "&msc SCRL_UP": "Scroll ↑"
