draw_config:
  n_columns: 1
  dark_mode: auto

parse_config:
  raw_binding_map:
    "&kp LCTRL": "⌃"
    "&kp LSHIFT": "⇧"
    "&kp LALT": "⌥"
    "&kp TAB": "⇥"
    "&kp BACKSPACE": "⌫"
    "&kp DELETE": "⌦"
    "&kp ESC": "⎋"
    "&kp SPACE": "␣"

    "&kp LEFT": "←"
    "&kp DOWN": "↓"
    "&kp UP": "↑"
    "&kp RIGHT": "→"

    "&lt 1 ENTER": { t: "⏎", h: "Arrow" }
    "&lt 2 SPACE": { t: "␣", h: "Num" }

    "&lm 1 LALT": { t: "⌥", h: "Arrow" }

    "&lang1_sh1": { t: "KANA", h: "⇧ Arrow" }
    "&lang2_gui": { t: "EISU", h: "⌘" }

    "&mkp LCLK": "L Click"
    "&mkp RCLK": "R Click"

    "&msc SCRL_DOWN": "Scroll ↓"
    "&msc SCRL_UP": "Scroll ↑"
